---
- name: Install mailx program
  apt: name=mailx state=present
  tags:
    - zabbix-server
    - email

- name: Create email script
  template: src=zabbixMailX.j2 dest={{ zabbix_server_alert_scripts_dir }}/zabbixEmail owner=root group=root mode=0755
  tags:
    - zabbix-server
    - email
