---
- name: install the zabbix rpm from a remote repo
  yum: name=http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm state=present
  when: ansible_distribution_major_version == '7'

- name: install the zabbix rpm from a remote repo
  fail: msg="No package for RedHat 6.x series"
  when: ansible_distribution_major_version == '6'

- name: Install package
  yum: name={{ zabbix_server_package }} state=present
  tags:
    - zabbix-server
